version: "3.9"

services:
  db:
    image: 'postgres:15-alpine'
    container_name: db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    ports:
      - '5433:5432'

  app:
    depends_on:
      - db
    image: 'verbanov/usermanager'
    build: .
    env_file: ./.env
    ports:
      - '8081:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url":"jdbc:postgresql://db:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
      "spring.datasource.username":"$POSTGRES_USER",
      "spring.datasource.password":"$POSTGRES_PASSWORD",
      "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.PostgreSQL81Dialect",
      "spring.jpa.hibernate.ddl-auto":"create-drop"
    }'
